"""Goals tab: placeholder UI; Goal Planning Agent lands in Phase 5."""

import streamlit as st


def render() -> None:
    st.markdown("## 🎯 Financial Goals")
    st.caption("Project savings toward retirement, a house, education, or any goal.")

    st.info(
        "🚧 **Goal Planning Agent is in active development.** "
        "The calculator below will compute projections in Phase 5."
    )

    # --- Savings Calculator ---
    st.markdown("### Savings Goal Calculator")
    col_left, col_right = st.columns(2)
    with col_left:
        st.number_input(
            "Target amount ($)",
            min_value=1000,
            value=100_000,
            step=1000,
            disabled=True,
        )
        st.number_input(
            "Time horizon (years)",
            min_value=1,
            max_value=50,
            value=10,
            disabled=True,
        )
    with col_right:
        st.number_input(
            "Current savings ($)",
            min_value=0,
            value=10_000,
            step=500,
            disabled=True,
        )
        st.slider(
            "Expected annual return (%)",
            min_value=1.0,
            max_value=15.0,
            value=7.0,
            step=0.5,
            disabled=True,
        )

    st.button(
        "📊 Calculate savings plan",
        use_container_width=True,
        disabled=True,
    )

    st.divider()

    st.markdown("### Coming in Phase 5")
    st.markdown(
        """
        - **Required monthly savings** to hit your target
        - **Year-by-year projection** as a table + line chart
        - **Sensitivity analysis** (what if return is 5%? 9%?)
        - **Inflation-adjusted target** (optional toggle)
        - **Goal feasibility score** based on income vs target
        - **Plain-language explanation** generated by the Goal Planning Agent
        """
    )