"""Goals tab: placeholder UI; agent lands in Phase 5."""

import streamlit as st


def render() -> None:
    st.markdown(
        '<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px;">'
        '<h2 style="margin:0;">🎯 Goals</h2>'
        '<span class="feature-badge badge-coming-soon">In development</span>'
        "</div>",
        unsafe_allow_html=True,
    )
    st.caption("Project savings toward retirement, a home, education, anything.")

    st.markdown("")

    st.markdown('<div class="section-eyebrow">Savings calculator</div>', unsafe_allow_html=True)
    c_left, c_right = st.columns(2)
    with c_left:
        st.number_input("Target amount ($)",     min_value=1000, value=100_000, step=1000, disabled=True)
        st.number_input("Time horizon (years)",  min_value=1, max_value=50, value=10, disabled=True)
    with c_right:
        st.number_input("Current savings ($)",   min_value=0, value=10_000, step=500, disabled=True)
        st.slider("Expected annual return (%)",  min_value=1.0, max_value=15.0, value=7.0, step=0.5, disabled=True)

    st.button("📊  Calculate plan", use_container_width=True, disabled=True)

    st.markdown("---")

    st.markdown('<div class="section-eyebrow">What\'s coming</div>', unsafe_allow_html=True)
    st.markdown(
        """
        - Required monthly savings to hit your target
        - Year-by-year projection as a table + line chart
        - Sensitivity analysis (what if return is 5%? 9%?)
        - Inflation-adjusted target (optional toggle)
        - Goal feasibility score based on income vs target
        - Plain-language explanation generated by the agent
        """
    )